"use client";
import { useState } from "react"; import Link from "next/link"; import { usePathname, useRouter } from "next/navigation"; import { useQuery, useQueryClient } from "@tanstack/react-query"; import { Home, Users, PlusCircle, Activity, UserRound, BarChart3, Upload, LogOut, Search, HandCoins } from "lucide-react"; import { ExpenseModal } from "@/components/app/expense-modal"; import { apiRequest } from "@/lib/api-client";
const nav=[["/dashboard","Dashboard",Home],["/groups","People",Users],["/settle","Settle",HandCoins],["/analytics","Analytics",BarChart3],["/import","Import",Upload],["/activity","Activity",Activity],["/search","Search",Search],["/profile","Profile",UserRound]] as const;
export function AppShell({children}:{children:React.ReactNode}){const path=usePathname(); const router=useRouter(); const queryClient=useQueryClient(); const [expenseOpen,setExpenseOpen]=useState(false); const me=useQuery({queryKey:["me"],queryFn:()=>apiRequest<any>("/api/me"),enabled:!path.startsWith("/login")&&!path.startsWith("/register")}); const groups=useQuery({queryKey:["groups"],queryFn:()=>apiRequest<any[]>("/api/groups"),enabled:!path.startsWith("/login")&&!path.startsWith("/register")}); async function logout(){await fetch("/api/auth/logout",{method:"POST"}); router.replace("/login"); router.refresh();} return <div className="min-h-screen md:grid md:grid-cols-[240px_1fr]">
<aside className="hidden border-r border-slate-200 p-4 dark:border-slate-800 md:flex md:flex-col"><h1 className="mb-8 text-2xl font-bold text-emerald-500">Splitwise</h1>{nav.map(([href,label,Icon])=><Link key={href} href={href} className={`mb-2 flex items-center gap-3 rounded-xl p-3 ${path.startsWith(href)?"bg-emerald-500 text-white":"hover:bg-slate-100 dark:hover:bg-slate-900"}`}><Icon size={18}/>{label}</Link>)}<button onClick={logout} className="mt-auto flex items-center gap-3 rounded-xl p-3 hover:bg-slate-100 dark:hover:bg-slate-900"><LogOut size={18}/>Logout</button></aside>
<main className="pb-24 md:pb-0">{children}</main>
<nav className="fixed inset-x-0 bottom-0 z-20 grid grid-cols-5 border-t bg-white p-2 dark:border-slate-800 dark:bg-slate-950 md:hidden">{[nav[0],nav[1]].map(([href,label,Icon])=><Link key={href} href={href} className={`flex flex-col items-center gap-1 text-xs ${path.startsWith(href)?"text-emerald-500":""}`}><Icon size={20}/>{label}</Link>)}<button type="button" onClick={()=>setExpenseOpen(true)} className="flex flex-col items-center gap-1 text-xs text-emerald-500"><PlusCircle size={28}/>Add</button>{[nav[5],nav[7]].map(([href,label,Icon])=><Link key={href} href={href} className={`flex flex-col items-center gap-1 text-xs ${path.startsWith(href)?"text-emerald-500":""}`}><Icon size={20}/>{label}</Link>)}</nav>
<ExpenseModal open={expenseOpen} onClose={()=>setExpenseOpen(false)} onSaved={()=>queryClient.invalidateQueries()} me={me.data} groups={groups.data??[]} />
</div>}
